### PR TITLE
Update to MAPL 2.6.6

### PR DESCRIPTION
**Pull request by mathomp4**
This updates GEOSgcm to use MAPL 2.6.6. This is zero-diff *except* for 2-moment microphysics which isn't. For some reason cleaning up some code in MAPL to do with profiling changes the 2-moment answers. Why? Our only thought at this point is some memory state issues in 2-moment?

Still, this is an important release. It has fixes for GEOSadas-to-MAPL2, updates to move to the new Baselibs, and I think GOCART2G might need it (@gmao-esherman could let us know). @tclune might know of other reasons we want MAPL 2.6.6

### CODE REVIEW

**Comment by mathomp4** [comment]
For @gmao-esherman, this is essentially MAPL `develop` which was released today. So, if your GOCART2G work required `develop`, hopefully you can move it to use MAPL 2.6.5.

**Comment by gmao-esherman** [comment]
> For @gmao-esherman, this is essentially MAPL `develop` which was released today. So, if your GOCART2G work required `develop`, hopefully you can move it to use MAPL 2.6.5.

Awesome, thank you Matt! I have been on develop because it has updates to HISTORY that GOCART2G needs. This is very useful because I can now use this tag in my components.yaml instead of just referencing develop.

**Comment by tclune** [comment]
This has a few things that NOAA had wanted.  None are crucial.

**Comment by mathomp4** [comment]
There is a bug in MAPL 2.6.5. Blocking this until a hotfix can be applied and 2.6.6 released

**Comment by mathomp4** [comment]
Okay I've updated this to use MAPL 2.6.6 which has the hotfix for the `Debug` issue. @gmao-esherman please move to use MAPL v2.6.6

**Review by sdrabenh — APPROVED** [review]

**Pull request merged**
