### PR TITLE
Update MOM6 to latest NOAA code

### PR DESCRIPTION
**Pull request by mathomp4**
This PR is really from @sanAkel and is updates needed to advance MOM6 in GEOS. It includes updates:

- FMS to `geos/2019.01.02+noaff.6` (zero-diff for AMIP and Coupled)
- MOM6 to `geos/v2.0.0` (zero-diff for Coupled)
- GEOSgcm_GridComp to *BRANCH* `feature/sanAkel/test_PR_gfdl-fms2` (see PR https://github.com/GEOS-ESM/GEOSgcm_GridComp/pull/416)

Of course, this latter one will be a *tag* of GEOSgcm_GridComp when all is well.

### CODE REVIEW

**Review by sanAkel — DISMISSED** [review]
This is great! Thanks! @mathomp4

**Review by sanAkel — APPROVED** [review]
This is a zero-diff change (particularly, for the coupled model).

**Review by sanAkel — DISMISSED** [review]

**Review by sanAkel — APPROVED** [review]
I don't know anything about workflows (here!)

**Comment by sanAkel** [comment]
🥳 @sdrabenh, all build tests pass! 

🏆 to @mathomp4!

**Comment by mathomp4** [comment]
Huh. I didn't think that would happen. Oh well, nice to see!

Though I'm confused as to where the AWS build test went...

**Review by tclune — APPROVED** [review]

**Review by sdrabenh — APPROVED** [review]

**Pull request merged**
