### PR TITLE
Updates for NH Build: fvdycore, ESMA_env, FV3 GC, GEOSgcm_App

### PR DESCRIPTION
**Pull request by mathomp4**
This pulls in fvdycore v1.1.5 which adds an option to the CMake step where you can add:
```
cmake ... -DHYDROSTATIC=ON/OFF
```
The default is `ON` which is currently what GEOS builds FV3 as. If you choose `OFF` then the FV core is built with extra preprocessor variables, `MOIST_CAPPA` and `USE_COND`.

### CODE REVIEW

**Comment by wmputman** [comment]
OK, so, this is going to get interesting, because with the NH build options, we can only run NH (hydrostatic runs with that build are completely invalid). So we are going to have to think through what we do to facilitate hydrostatic/nonhydrostatic options for build/run

**Comment by aoloso** [comment]
Perhaps look into using run time parameters?

**Comment by mathomp4** [comment]
> OK, so, this is going to get interesting, because with the NH build options, we can only run NH (hydrostatic runs with that build are completely invalid). So we are going to have to think through what we do to facilitate hydrostatic/nonhydrostatic options for build/run

You aren't kidding. I just tried running C12->C720 with the NH build and, uh, they all failed to run. Should that be? I mean, I understand for C12, but C720? My `fvcore_layout.rc` has:
```
&fv_core_nml
  k_split     = 2
  Make_NH     = .T.
  hydrostatic = .F.
  do_sat_adj = .F.
  z_tracer    = .T.
  nwat       =  3
/
```
which I think is right for what I see in `gcm_setup`.

Do I perhaps need to spin up new restarts using an NH build of FV3?

**Comment by aoloso** [comment]
> > OK, so, this is going to get interesting, because with the NH build options, we can only run NH (hydrostatic runs with that build are completely invalid). So we are going to have to think through what we do to facilitate hydrostatic/nonhydrostatic options for build/run
> 
> You aren't kidding. I just tried running C12->C720 with the NH build and, uh, they all failed to run. Should that be? I mean, I understand for C12, but C720? My `fvcore_layout.rc` has:
> 
> ```
> &fv_core_nml
>   k_split     = 2
>   Make_NH     = .T.
>   hydrostatic = .F.
>   do_sat_adj = .F.
>   z_tracer    = .T.
>   nwat       =  3
> /
> ```
> 
> which I think is right for what I see in `gcm_setup`.
> 
> Do I perhaps need to spin up new restarts using an NH build of FV3?

Did you try coldstart?

**Comment by mathomp4** [comment]
An update. It turns out the reason all my runs failed is that my restarts seem to be "too old". I apparently regridded them long enough ago (years?) and I've pushed my luck as far as it'll go. 

If I regrid the restarts using the latest model, I can indeed run non-hydrostatic! Even at C12 it looks like. So that is good.

**Comment by mathomp4** [comment]
And now more questions for @wmputman (and @sdrabenh ). In my testing it looks like *if* you build for non-hydrostatic, you should *not* select hydrostatic in `gcm_setup`. Model will crash! (I think if you build for hydrostatic, the `gcm_setup` NH selection might work...though the results are probably garbage?)

So, I suppose a question is: Should the `gcm_setup` hydrostatic question default to what the build is? That is, if you build `-DHYDROSTATIC=ON` then the default answer in `gcm_setup` is Hydrostatic=YES, and vice versa?

And I guess, should I add a new option to `parallel_build.csh` for hydro/nonhydro?

**Comment by mathomp4** [comment]
As can be seen above, I've make draft PRs in App, FV3 GC, and env for more support of this.

**Review by sdrabenh — APPROVED** [review]

**Pull request merged**
