### PR TITLE
Uppercase ESMF_ROOT for Spack

### LINKED ISSUE #767: Need to search for uppercase ESMF_ROOT instead of esmf_ROOT in CMakeLists.txt with next spack-stack release
WIth spack-stack-1.7.0, we revert to the spack develop version of `UPPERCASEPACKAGENAME_ROOT` instead of `CaseSensitivePackageName_ROOT`. This will require changing `esmf_ROOT` to `ESMF_ROOT` in `CMakelistst.txt:

https://github.com/GEOS-ESM/GEOSgcm/blob/53409fd14ec9784246dfef7cc1063864bbc15565/CMakeLists.txt#L60

I am surprised to find the spack-stack convention (`CaseSensitivePackageName_ROOT`) in `CMakeLists.txt`, since I though GEOS so far didn't use spack-stack. If your build systems also set `esmf_ROOT`, can you either consider changing those to `ESMF_ROOT` as well, or check for both `esmf_ROOT` and `ESMF_ROOT` in`CMakeLists.txt`, please?

```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index a5e6810..cef7ff7 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -57,9 +57,9 @@ if (NOT Baselibs_FOUND)
   endif()

   if (NOT TARGET esmf)
-    if (DEFINED ENV{esmf_ROOT})
-      message (STATUS "Found esmf_ROOT in environment: $ENV{esmf_ROOT}")
-      find_path(ESMF_CMAKE_PATH FindESMF.cmake HINTS "$ENV{esmf_ROOT}/cmake")
+         if (DEFINED ENV{ESMF_ROOT})
+                 message (STATUS "Found ESMF_ROOT in environment: $ENV{ESMF_ROOT}")
+                 find_path(ESMF_CMAKE_PATH FindESMF.cmake HINTS "$ENV{ESMF_ROOT}/cmake")
       message (STATUS "Found FindESMF.cmake in: ${ESMF_CMAKE_PATH}")
       if (ESMF_CMAKE_PATH)
         message (STATUS "Appending to CMAKE_PREFIX_PATH: ${ESMF_CMAKE_PATH}")
```

### PR DESCRIPTION
**Pull request by mathomp4**
Closes #767 

Per @climbfuji, we should use `ESMF_ROOT` instead of `esmf_ROOT` as that is more conventional.

This does not affect GEOS-with-Baselibs runs as we are not in this block.

Note, I've also uppercased the target to `ESMF` as that is what ESMF itself provides. Eventually we should change this to `ESMF::ESMF` but that will need to wait for ESMF 8.6.1

### CODE REVIEW

**Comment by climbfuji** [comment]
Thanks @mathomp4 ! Maybe we can wait merging this until the new spack-stack using the uppercase version is rolled out?

**Comment by mathomp4** [comment]
@climbfuji If you can test it to make sure it works, that's great, but we can hold off as long as you'd like as it doesn't affect our Baselibs builds. 

Once you need it let us know.

**Comment by mathomp4** [comment]
I'll mark this draft to make sure we don't merge until wanted.

**Review by climbfuji — APPROVED** [review]
Works for me, thanks very much! I'll let you know when the time is ready to merge.

**Comment by climbfuji** [comment]
Uhh, didn't we revert this uppercase change because of all the cmake warnings? And raised it with the spack developers?

**Comment by mathomp4** [comment]
> Uhh, didn't we revert this uppercase change because of all the cmake warnings? And raised it with the spack developers?

@climbfuji This has been kept draft for now. We can close it if you like. I wasn't sure if you still wanted it or not so... Up to you!

**Comment by climbfuji** [comment]
I checked on my mac, and we indeed reverted to case-preserving `packageName_ROOT`. Let's close this. Sorry for the hassle!

**Comment by mathomp4** [comment]
> I checked on my mac, and we indeed reverted to case-preserving `packageName_ROOT`. Let's close this. Sorry for the hassle!

Eh. Wasn't exactly a hard PR to make :) Closing!

**Pull request closed without merging**
