### PR TITLE
Update FMS: Fix for flush issue on macOS

### PR DESCRIPTION
**Pull request by mathomp4**
This is a patch update to FMS which changes all the `call flush()` in FMS to `flush()` to allow Intel Fortran on macOS to work (@tclune knows more of the details...something to do with the shared object libraries).

I have tested with AMIP, MOM5, and MOM6 and all run and seem zero-diff. But, it would good if @yvikhlya or @sanAkel can make sure nothing broke in coupled-space. (I'd be very sad if changing `flush` statements changed the model state. 😄 )

### CODE REVIEW

**Comment by tclune** [comment]
I certainly don't know much beyond this.  Basically Intel appears to share some code between the FLUSH intrinsic and the Intel subroutine extension FLUSH.   Somewhere or another there is a check in their code that disallows negative unit numbers even though those now arise often with the `NEWUNIT` argument to open.    The exact circumstances appear to be very subtle though.

**Comment by sanAkel** [comment]
@mathomp4 , @tclune I can double check this next week

**Review by sanAkel — APPROVED** [review]
Checked for zero-diff for following restarts (6 hour run - that's good enough for me!):
- fvcore_internal_rst

and with following ocean_models:

1. [x] MOM5 : ocean_temp_salt.res.nc
2. [x] MOM6 : MOM.res.nc

@mathomp4 , all good! 😃

**Comment by mathomp4** [comment]
@sanAkel Thanks! We can pull this in as needed, I suppose. Though it's not crucial at the moment.

**Review by sdrabenh — APPROVED** [review]

**Pull request merged**
