### PR TITLE
Update version for GEOSchem_GridComp and GOCART

### PR DESCRIPTION
**Pull request by mmanyin**
Non-zero diff due to new QFED version (AMIP simulations after 20th cent).

### CODE REVIEW

**Comment by mmanyin** [comment]
Now we uptick TR, in addition to CHEMISTRY, GOCART and GMI.
The standard 4 tracers are zero-diff, but Be and Pb species are non-zero-diff very slightly due to a different SZA calculation.

**Comment by mathomp4** [comment]
@mmanyin A query: Is there a reason you have GOCART v2.1.3 here, be it science or otherwise? 

Would you be amenable to moving up to v2.2.1? I think that version has changes and fixes we'd  need and we'd have to back-port to v2.1.x if we stayed on that.

**Comment by mmanyin** [comment]
@mathomp4  As far as I'm concerned, it would be fine to update GOCART to a more recent tag. This PR was meant as a suggestion to the gatekeeper that new versions of CHEM and GMI (and now TR) are available for use, and since the new CHEM revised the QFED paths, I also upticked GOCART to v2.1.3 because it  included new QFED paths as well.  I was leaving the science analysis of this GOCART version (and any future versions) to @sdrabenh and others.

**Comment by mathomp4** [comment]
I realized I never updated this to GOCART v2.2.1. Oops. Doing it now...

**Comment by mathomp4** [comment]
Tested this today and still non-zero-diff as expected. But it works, which is nice! Hopefully we get it in soon.

**Review by sdrabenh — APPROVED** [review]

**Pull request merged**
