### PR TITLE
Ocean maintenance 

### PR DESCRIPTION
**Pull request by sanAkel**
Uptick versions of MOM6 and Ocean GC.

No change in answers.

### CODE REVIEW

**Comment by mathomp4** [comment]
Hmm. GNU is not happy running coupled.

**Comment by sanAkel** [comment]
> Hmm. GNU is not happy running coupled.

I'll need to reproduce the error in the diabatic driver.

**Comment by sanAkel** [comment]
> > Hmm. GNU is not happy running coupled.
> 
> I'll need to reproduce the error in the diabatic driver.

Is the CI running this resolution: https://github.com/GEOS-ESM/GEOS_OceanGridComp/tree/develop/MOM6_GEOSPlug/mom6_app/72x36 ? Had no issues with ifort!

**Comment by mathomp4** [comment]
> > > Hmm. GNU is not happy running coupled.
> > 
> > 
> > I'll need to reproduce the error in the diabatic driver.
> 
> Is the CI running this resolution: https://github.com/GEOS-ESM/GEOS_OceanGridComp/tree/develop/MOM6_GEOSPlug/mom6_app/72x36 ? Had no issues with ifort!

Yes. It runs my usual 1-day c12 1x6 job I think.

**Comment by sanAkel** [comment]
(to remind) We'll get to this PR when [this PR](https://github.com/mom-ocean/MOM6/pull/1605) is merged.

**Comment by sanAkel** [comment]
@mathomp4 your [PR](https://github.com/mom-ocean/MOM6/pull/1605) has been merged. 

- Please update our [MOM6 fork](https://github.com/GEOS-ESM/MOM6).
- Once ⬆️ is done, you/I can make a new [release](https://github.com/GEOS-ESM/MOM6/releases)
- Re-try [this](https://github.com/GEOS-ESM/GEOSgcm/pull/629) PR.

**Comment by mathomp4** [comment]
> @mathomp4 your [PR](https://github.com/mom-ocean/MOM6/pull/1605) has been merged.
> 
> * Please update our [MOM6 fork](https://github.com/GEOS-ESM/MOM6).

Nice! Fork has been updated!

**Comment by mathomp4** [comment]
> @mathomp4 can you please have the test(s) run again?

@sanAkel Something is off. I don't think geos/v2.2.1 got the GNU fix commit in. The tag is based on two commits back.

**Comment by sanAkel** [comment]
> > @mathomp4 can you please have the test(s) run again?
> 
> @sanAkel Something is off. I don't think geos/v2.2.1 got the GNU fix commit in. The tag is based on two commits back.

Sorry @mathomp4, I didn't delete the (old) tag, see [this one](https://github.com/GEOS-ESM/MOM6/releases/tag/geos%2Fv2.2.1). If okay, please try again! Thanks!

**Comment by mathomp4** [comment]
Huzzah! 😄

**Comment by sanAkel** [comment]
@mathomp4 can you ✅ reviewer box?!!

**Comment by mathomp4** [comment]
> @mathomp4 can you ✅ reviewer box?!!

I can, but if I do I approve for GCM Gatekeepers as well. I usually leave that to @sdrabenh 

Would you like this in main quickly? Or do you require a tag?

**Comment by sanAkel** [comment]
> > @mathomp4 can you ✅ reviewer box?!!
> 
> I can, but if I do I approve for GCM Gatekeepers as well. I usually leave that to @sdrabenh
> 
> Would you like this in main quickly? Or do you require a tag?

I don't see any urgency. Let it go through @sdrabenh ... Thank you!

**Pull request merged**
