### PR TITLE
MOM6 in GEOS

### PR DESCRIPTION
**Pull request by aerorahul**
This PR
- enables building GEOS with MOM6.
- Brings GSW-Fortran as an external repository (needed for MOM6).

### CODE REVIEW

**Comment by tclune** [comment]
@aerorahul  Just to be clear, because we are using a _fork_ we had to use the same name as GFDL, which is just "FMS".     So the "they" is GFDL.    We are still mounting it as GFDL_fms via externals, I believe.

**Comment by tclune** [comment]
@aerorahul  Maybe you just mean the section label in the externals cfg file?   Those don't really mean anything, and I'm fine with changing that to GFDL_fms.    I made  my entry separately from yours and had not realized the precedent at the time.

But we should be consistent going forward to avoid confusion.    Indeed, I'm tempted to change the mount point to @FMS while we are at it.   This would be more consistent with the big picture even if it is a change from the GEOS perspective.   Thoughts?

**Comment by aerorahul** [comment]
> @aerorahul Maybe you just mean the section label in the externals cfg file? Those don't really mean anything, and I'm fine with changing that to GFDL_fms. I made my entry separately from yours and had not realized the precedent at the time.
> 
> But we should be consistent going forward to avoid confusion. Indeed, I'm tempted to change the mount point to @fms while we are at it. This would be more consistent with the big picture even if it is a change from the GEOS perspective. Thoughts?

I suggest the mount point be consistent with the section label.  In this case @ fms.  The libraries would then be fms_r4 and fms_r8 respectively.

**Comment by aerorahul** [comment]
I am closing this PR and will re-open with 2 separate PR's
The first one will be purely structural, where new code will be added but neither be compiled or exercised.
The second PR will have modifications that will exercise the newly added code, but will be zero-diff with respect to develop.

**Pull request closed without merging**
